// <auto-generated />
using System;
using HotelBookingAppWebApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HotelBookingAppWebApi.Migrations
{
    [DbContext(typeof(HotelBookingContext))]
    [Migration("20260325000000_FullSystemUpdate")]
    partial class FullSystemUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is auto-generated — run `dotnet ef migrations add` to regenerate
        }
    }
}
