// <auto-generated />
using System;
using HotelBookingAppWebApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBookingAppWebApi.Migrations
{
    [DbContext(typeof(HotelBookingContext))]
    [Migration("20260223041554_UpdateUserPasswordToByteArray")]
    partial class UpdateUserPasswordToByteArray
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelBookingAppWebApi.Models.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            Address = "MG Road",
                            City = "Chennai",
                            ContactNumber = "9000000001",
                            Description = "Luxury hotel",
                            ImageUrl = "img1.jpg",
                            IsActive = true,
                            Name = "Grand Palace"
                        },
                        new
                        {
                            HotelId = 2,
                            Address = "Beach Road",
                            City = "Goa",
                            ContactNumber = "9000000002",
                            Description = "Beach side stay",
                            ImageUrl = "img2.jpg",
                            IsActive = true,
                            Name = "Sea View Resort"
                        },
                        new
                        {
                            HotelId = 3,
                            Address = "Hill Top",
                            City = "Ooty",
                            ContactNumber = "9000000003",
                            Description = "Hill station hotel",
                            ImageUrl = "img3.jpg",
                            IsActive = true,
                            Name = "Mountain Retreat"
                        },
                        new
                        {
                            HotelId = 4,
                            Address = "Downtown",
                            City = "Bangalore",
                            ContactNumber = "9000000004",
                            Description = "Business hotel",
                            ImageUrl = "img4.jpg",
                            IsActive = true,
                            Name = "City Inn"
                        },
                        new
                        {
                            HotelId = 5,
                            Address = "Palace Road",
                            City = "Jaipur",
                            ContactNumber = "9000000005",
                            Description = "Heritage stay",
                            ImageUrl = "img5.jpg",
                            IsActive = true,
                            Name = "Royal Heritage"
                        });
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ReservationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("HotelId");

                    b.HasIndex("ReservationCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.ReservationRoom", b =>
                {
                    b.Property<int>("ReservationRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationRoomId"));

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("ReservationRoomId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("RoomId");

                    b.ToTable("ReservationRooms");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Floor = 1,
                            HotelId = 1,
                            IsActive = true,
                            RoomNumber = "101",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 2,
                            Floor = 1,
                            HotelId = 1,
                            IsActive = true,
                            RoomNumber = "102",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 3,
                            Floor = 2,
                            HotelId = 2,
                            IsActive = true,
                            RoomNumber = "201",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 4,
                            Floor = 3,
                            HotelId = 3,
                            IsActive = true,
                            RoomNumber = "301",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 5,
                            Floor = 4,
                            HotelId = 4,
                            IsActive = true,
                            RoomNumber = "401",
                            RoomTypeId = 5
                        });
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.RoomType", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeId"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomTypeId");

                    b.HasIndex("HotelId");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            RoomTypeId = 1,
                            Amenities = "AC,TV,WiFi",
                            Description = "Deluxe Room",
                            HotelId = 1,
                            IsActive = true,
                            MaxOccupancy = 2,
                            Name = "Deluxe"
                        },
                        new
                        {
                            RoomTypeId = 2,
                            Amenities = "AC,TV,WiFi,MiniBar",
                            Description = "Luxury Suite",
                            HotelId = 1,
                            IsActive = true,
                            MaxOccupancy = 4,
                            Name = "Suite"
                        },
                        new
                        {
                            RoomTypeId = 3,
                            Amenities = "Fan,TV",
                            Description = "Standard Room",
                            HotelId = 2,
                            IsActive = true,
                            MaxOccupancy = 2,
                            Name = "Standard"
                        },
                        new
                        {
                            RoomTypeId = 4,
                            Amenities = "AC,TV,WiFi",
                            Description = "Family Room",
                            HotelId = 3,
                            IsActive = true,
                            MaxOccupancy = 5,
                            Name = "Family"
                        },
                        new
                        {
                            RoomTypeId = 5,
                            Amenities = "AC,TV,WiFi,Desk",
                            Description = "Executive Room",
                            HotelId = 4,
                            IsActive = true,
                            MaxOccupancy = 3,
                            Name = "Executive"
                        });
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.RoomTypeInventory", b =>
                {
                    b.Property<int>("RoomTypeInventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeInventoryId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ReservedInventory")
                        .HasColumnType("int");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalInventory")
                        .HasColumnType("int");

                    b.HasKey("RoomTypeInventoryId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("RoomTypeInventories");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.RoomTypeRate", b =>
                {
                    b.Property<int>("RoomTypeRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeRateId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("RoomTypeRateId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("RoomTypeRates");

                    b.HasData(
                        new
                        {
                            RoomTypeRateId = 1,
                            EndDate = new DateOnly(2026, 12, 31),
                            Rate = 2500m,
                            RoomTypeId = 1,
                            StartDate = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            RoomTypeRateId = 2,
                            EndDate = new DateOnly(2026, 12, 31),
                            Rate = 4500m,
                            RoomTypeId = 2,
                            StartDate = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            RoomTypeRateId = 3,
                            EndDate = new DateOnly(2026, 12, 31),
                            Rate = 1800m,
                            RoomTypeId = 3,
                            StartDate = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            RoomTypeRateId = 4,
                            EndDate = new DateOnly(2026, 12, 31),
                            Rate = 3200m,
                            RoomTypeId = 4,
                            StartDate = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            RoomTypeRateId = 5,
                            EndDate = new DateOnly(2026, 12, 31),
                            Rate = 4000m,
                            RoomTypeId = 5,
                            StartDate = new DateOnly(2026, 1, 1)
                        });
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@hotel.com",
                            IsActive = true,
                            PasswordHash = new byte[] { 1, 2, 3, 4, 5 },
                            PasswordSalt = new byte[] { 5, 4, 3, 2, 1 },
                            Phone = "9999999999",
                            Role = 1,
                            UserName = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "john@mail.com",
                            IsActive = true,
                            PasswordHash = new byte[] { 10, 20, 30 },
                            PasswordSalt = new byte[] { 30, 20, 10 },
                            Phone = "8888888888",
                            Role = 0,
                            UserName = "John"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "alice@mail.com",
                            IsActive = true,
                            PasswordHash = new byte[] { 11, 22, 33 },
                            PasswordSalt = new byte[] { 33, 22, 11 },
                            Phone = "7777777777",
                            Role = 0,
                            UserName = "Alice"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "bob@mail.com",
                            IsActive = true,
                            PasswordHash = new byte[] { 44, 55, 66 },
                            PasswordSalt = new byte[] { 66, 55, 44 },
                            Phone = "6666666666",
                            Role = 0,
                            UserName = "Bob"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "charlie@mail.com",
                            IsActive = true,
                            PasswordHash = new byte[] { 77, 88, 99 },
                            PasswordSalt = new byte[] { 99, 88, 77 },
                            Phone = "5555555555",
                            Role = 0,
                            UserName = "Charlie"
                        });
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.Reservation", b =>
                {
                    b.HasOne("HotelBookingAppWebApi.Models.Hotel", "Hotel")
                        .WithMany("Reservations")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBookingAppWebApi.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.ReservationRoom", b =>
                {
                    b.HasOne("HotelBookingAppWebApi.Models.Reservation", "Reservation")
                        .WithMany("ReservationRooms")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBookingAppWebApi.Models.Room", "Room")
                        .WithMany("ReservationRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.Review", b =>
                {
                    b.HasOne("HotelBookingAppWebApi.Models.Hotel", "Hotel")
                        .WithMany("Reviews")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBookingAppWebApi.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.Room", b =>
                {
                    b.HasOne("HotelBookingAppWebApi.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBookingAppWebApi.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.RoomType", b =>
                {
                    b.HasOne("HotelBookingAppWebApi.Models.Hotel", "Hotel")
                        .WithMany("RoomTypes")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.RoomTypeInventory", b =>
                {
                    b.HasOne("HotelBookingAppWebApi.Models.RoomType", "RoomType")
                        .WithMany("Inventories")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.RoomTypeRate", b =>
                {
                    b.HasOne("HotelBookingAppWebApi.Models.RoomType", "RoomType")
                        .WithMany("Rates")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.Transaction", b =>
                {
                    b.HasOne("HotelBookingAppWebApi.Models.Reservation", "Reservation")
                        .WithMany("Transactions")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.Hotel", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Reviews");

                    b.Navigation("RoomTypes");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.Reservation", b =>
                {
                    b.Navigation("ReservationRooms");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.Room", b =>
                {
                    b.Navigation("ReservationRooms");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.RoomType", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("Rates");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelBookingAppWebApi.Models.User", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
