select * from Users
select * from Hotels
select * from RoomTypes
select * from UserProfileDetails
select * from Rooms
select * from RoomTypeRates
select * from RoomTypeInventories
select * from Reservations
select * from ReservationRooms
select * from Transactions
select * from Reviews
select * from Logs